### ISSUE TITLE
Rounding errors

### ISSUE THREAD

**Issue by nmunnich** [caksoylar/zmk-physical-layout-converter#1]
In the default shown when you open the website, if you change the devicetree key marked as x 300 y 28 to y29, then upon save it will revert back to y28.

**Comment by caksoylar** [comment]
It's a rounding issue alright:
![image](https://github.com/user-attachments/assets/ef5b0078-4a46-4b58-a64d-d00066a01e8b)

I'll change the code to round when converting to DTS.
